// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToyWorld.API.Models
{
    public partial class User
    {
        public User()
        {
            Toys = new HashSet<Toy>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Toy> Toys { get; set; }
    }
}